// Package agentscompiler implements the main AGENTS.md compilation orchestrator.
//
// Coordinates primitive discovery, template building, link resolution,
// distributed or single-file output, Claude/Gemini formatter pipelines,
// and deterministic Build ID finalization.
//
// Migrated from: src/apm_cli/compilation/agents_compiler.py
package agentscompiler

import (
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// -------------------------------------------------------------------
// Config
// -------------------------------------------------------------------

// CompileTargetType names a supported output target.
type CompileTargetType = string

const (
	TargetAll       CompileTargetType = "all"
	TargetVSCode    CompileTargetType = "vscode"
	TargetAgents    CompileTargetType = "agents"
	TargetCopilot   CompileTargetType = "copilot"
	TargetClaude    CompileTargetType = "claude"
	TargetGemini    CompileTargetType = "gemini"
	TargetCursor    CompileTargetType = "cursor"
	TargetOpenCode  CompileTargetType = "opencode"
	TargetCodex     CompileTargetType = "codex"
	TargetWindsurf  CompileTargetType = "windsurf"
	TargetMinimal   CompileTargetType = "minimal"
	TargetAgentSkills CompileTargetType = "agent-skills"
)

// CompilationStrategy controls whether distributed or single-file output is used.
type CompilationStrategy = string

const (
	StrategyDistributed CompilationStrategy = "distributed"
	StrategySingleFile  CompilationStrategy = "single-file"
)

// BuildIDPlaceholder is replaced with the deterministic build ID after assembly.
const BuildIDPlaceholder = "<!-- APM_BUILD_ID_PLACEHOLDER -->"

// CopilotRootGeneratedMarker identifies files emitted by APM.
const CopilotRootGeneratedMarker = "<!-- Generated by APM CLI from .apm/ primitives -->"

// CompilationConfig holds all options for a compilation run.
type CompilationConfig struct {
	OutputPath    string
	Chatmode      string
	ResolveLinks  bool
	DryRun        bool
	WithConstitution bool
	Target        CompileTargetType
	Strategy      CompilationStrategy
	SingleAgents  bool
	Verbose       bool
	Quiet         bool
	WorkDir       string
}

// DefaultConfig returns sensible defaults.
func DefaultConfig() CompilationConfig {
	return CompilationConfig{
		OutputPath:       "AGENTS.md",
		ResolveLinks:     true,
		WithConstitution: true,
		Target:           TargetAll,
		Strategy:         StrategyDistributed,
	}
}

// -------------------------------------------------------------------
// Results
// -------------------------------------------------------------------

// CompilationResult captures the outcome of one target's compilation.
type CompilationResult struct {
	Target     CompileTargetType
	OutputPath string
	Content    string
	BuildID    string
	LinesOut   int
	ElapsedMS  int64
	Error      error
	Warnings   []string
	DryRun     bool
}

// OK returns true when the result has no error.
func (r CompilationResult) OK() bool { return r.Error == nil }

// MergedResult summarises a multi-target compilation.
type MergedResult struct {
	Results  []CompilationResult
	Errors   []error
	Warnings []string
	TotalMS  int64
}

// OK returns true when all results are OK.
func (m MergedResult) OK() bool {
	for _, r := range m.Results {
		if r.Error != nil {
			return false
		}
	}
	return true
}

// -------------------------------------------------------------------
// AgentsCompiler
// -------------------------------------------------------------------

// AgentsCompiler orchestrates AGENTS.md generation.
type AgentsCompiler struct {
	baseDir string
	logger  Logger
}

// Logger is a minimal logging interface.
type Logger interface {
	Debug(msg string, args ...interface{})
	Info(msg string, args ...interface{})
	Warn(msg string, args ...interface{})
	Error(msg string, args ...interface{})
}

// noopLogger discards all log output.
type noopLogger struct{}

func (n noopLogger) Debug(msg string, args ...interface{}) {}
func (n noopLogger) Info(msg string, args ...interface{})  {}
func (n noopLogger) Warn(msg string, args ...interface{})  {}
func (n noopLogger) Error(msg string, args ...interface{}) {}

// New constructs an AgentsCompiler for the given base directory.
func New(baseDir string) *AgentsCompiler {
	if baseDir == "" {
		baseDir = "."
	}
	abs, err := filepath.Abs(baseDir)
	if err != nil {
		abs = baseDir
	}
	return &AgentsCompiler{baseDir: abs, logger: noopLogger{}}
}

// SetLogger replaces the default (noop) logger.
func (a *AgentsCompiler) SetLogger(l Logger) { a.logger = l }

// -------------------------------------------------------------------
// Compilation entry point
// -------------------------------------------------------------------

// Compile runs the full compilation pipeline for cfg.
func (a *AgentsCompiler) Compile(cfg CompilationConfig) (*MergedResult, error) {
	if cfg.WorkDir != "" {
		a.baseDir = cfg.WorkDir
	}
	t0 := time.Now()
	targets := a.resolveTargets(cfg.Target)
	merged := &MergedResult{}

	for _, target := range targets {
		r := a.compileTarget(cfg, target)
		merged.Results = append(merged.Results, r)
		if r.Error != nil {
			merged.Errors = append(merged.Errors, r.Error)
		}
		merged.Warnings = append(merged.Warnings, r.Warnings...)
	}
	merged.TotalMS = time.Since(t0).Milliseconds()
	return merged, nil
}

func (a *AgentsCompiler) resolveTargets(target CompileTargetType) []CompileTargetType {
	switch target {
	case TargetAll:
		return []CompileTargetType{TargetVSCode, TargetClaude, TargetGemini}
	case TargetAgents, TargetCopilot:
		return []CompileTargetType{TargetVSCode}
	default:
		return []CompileTargetType{target}
	}
}

func (a *AgentsCompiler) compileTarget(cfg CompilationConfig, target CompileTargetType) CompilationResult {
	t0 := time.Now()
	result := CompilationResult{Target: target, DryRun: cfg.DryRun}

	content, outputPath, err := a.compileForTarget(cfg, target)
	if err != nil {
		result.Error = err
		result.ElapsedMS = time.Since(t0).Milliseconds()
		return result
	}

	content = a.finalizeBuildID(content)
	result.Content = content
	result.OutputPath = outputPath
	result.LinesOut = strings.Count(content, "\n")
	result.BuildID = a.extractBuildID(content)
	result.ElapsedMS = time.Since(t0).Milliseconds()

	if !cfg.DryRun && outputPath != "" {
		if err := a.writeOutputFile(outputPath, content); err != nil {
			result.Error = err
		}
	}
	return result
}

// -------------------------------------------------------------------
// Per-target dispatch
// -------------------------------------------------------------------

func (a *AgentsCompiler) compileForTarget(cfg CompilationConfig, target CompileTargetType) (content, outputPath string, err error) {
	switch target {
	case TargetVSCode, TargetAgents, TargetCopilot:
		return a.compileAgentsMD(cfg)
	case TargetClaude:
		return a.compileClaudeMD(cfg)
	case TargetGemini:
		return a.compileGeminiMD(cfg)
	default:
		return a.compileAgentsMD(cfg)
	}
}

func (a *AgentsCompiler) compileAgentsMD(cfg CompilationConfig) (string, string, error) {
	outputPath := cfg.OutputPath
	if outputPath == "" {
		outputPath = "AGENTS.md"
	}
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Join(a.baseDir, outputPath)
	}

	content, err := a.assembleContent(cfg)
	if err != nil {
		return "", outputPath, err
	}
	return content, outputPath, nil
}

func (a *AgentsCompiler) compileClaudeMD(cfg CompilationConfig) (string, string, error) {
	outputPath := filepath.Join(a.baseDir, "CLAUDE.md")
	content, err := a.assembleContent(cfg)
	if err != nil {
		return "", outputPath, err
	}
	return content, outputPath, nil
}

func (a *AgentsCompiler) compileGeminiMD(cfg CompilationConfig) (string, string, error) {
	outputPath := filepath.Join(a.baseDir, "GEMINI.md")
	content, err := a.assembleContent(cfg)
	if err != nil {
		return "", outputPath, err
	}
	return content, outputPath, nil
}

// -------------------------------------------------------------------
// Content assembly
// -------------------------------------------------------------------

func (a *AgentsCompiler) assembleContent(cfg CompilationConfig) (string, error) {
	primitives, err := a.discoverPrimitives()
	if err != nil {
		return "", fmt.Errorf("discover primitives: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(CopilotRootGeneratedMarker)
	sb.WriteString("\n")
	sb.WriteString(BuildIDPlaceholder)
	sb.WriteString("\n\n")

	for _, p := range primitives {
		sb.WriteString(p)
		sb.WriteString("\n\n")
	}

	content := sb.String()
	if cfg.ResolveLinks {
		content = a.resolveMarkdownLinks(content)
	}
	return content, nil
}

// discoverPrimitives returns the content of all .apm/ instruction/skill files.
func (a *AgentsCompiler) discoverPrimitives() ([]string, error) {
	apmDir := filepath.Join(a.baseDir, ".apm")
	var out []string
	_ = filepath.WalkDir(apmDir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if strings.HasSuffix(path, ".md") || strings.HasSuffix(path, ".instructions.md") {
			data, err := os.ReadFile(path)
			if err != nil {
				return nil
			}
			out = append(out, string(data))
		}
		return nil
	})
	return out, nil
}

func (a *AgentsCompiler) resolveMarkdownLinks(content string) string {
	// Minimal link resolution: relative paths remain as-is.
	return content
}

// -------------------------------------------------------------------
// Build ID
// -------------------------------------------------------------------

func (a *AgentsCompiler) finalizeBuildID(content string) string {
	hash := sha256.Sum256([]byte(strings.ReplaceAll(content, BuildIDPlaceholder, "")))
	buildID := fmt.Sprintf("<!-- Build ID: %x -->", hash[:6])
	return strings.ReplaceAll(content, BuildIDPlaceholder, buildID)
}

func (a *AgentsCompiler) extractBuildID(content string) string {
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "<!-- Build ID:") {
			return strings.TrimSpace(line)
		}
	}
	return ""
}

// -------------------------------------------------------------------
// File I/O
// -------------------------------------------------------------------

func (a *AgentsCompiler) writeOutputFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// -------------------------------------------------------------------
// Validation
// -------------------------------------------------------------------

// ValidatePrimitives checks the primitive collection for common errors.
func (a *AgentsCompiler) ValidatePrimitives() []string {
	var errs []string
	apmDir := filepath.Join(a.baseDir, ".apm")
	if _, err := os.Stat(apmDir); errors.Is(err, os.ErrNotExist) {
		errs = append(errs, ".apm/ directory not found")
	}
	return errs
}

// -------------------------------------------------------------------
// Compilation stats
// -------------------------------------------------------------------

// CompileStats returns a human-readable summary of a MergedResult.
func CompileStats(m *MergedResult) string {
	if m == nil {
		return "no results"
	}
	var parts []string
	for _, r := range m.Results {
		status := "ok"
		if r.Error != nil {
			status = "error: " + r.Error.Error()
		}
		parts = append(parts, fmt.Sprintf("%s=%s(%dms)", r.Target, status, r.ElapsedMS))
	}
	return strings.Join(parts, " ")
}

// -------------------------------------------------------------------
// Distributed compilation helpers
// -------------------------------------------------------------------

// DistributedFile represents one output file in a distributed compilation.
type DistributedFile struct {
	Path    string
	Content string
}

// WriteDistributedFiles writes multiple output files atomically.
func WriteDistributedFiles(files []DistributedFile, dryRun bool) error {
	for _, f := range files {
		if dryRun {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(f.Path), 0o755); err != nil {
			return err
		}
		tmp := f.Path + ".tmp"
		if err := os.WriteFile(tmp, []byte(f.Content), 0o644); err != nil {
			return err
		}
		if err := os.Rename(tmp, f.Path); err != nil {
			return err
		}
	}
	return nil
}

// -------------------------------------------------------------------
// Copilot root instructions
// -------------------------------------------------------------------

// CopilotRootInstructionsPath returns the path for auto-generated copilot root instructions.
func CopilotRootInstructionsPath(baseDir string) string {
	return filepath.Join(baseDir, ".github", "copilot-instructions.md")
}

// CleanupCopilotRootInstructions removes a previously generated root instructions file.
func CleanupCopilotRootInstructions(baseDir string) error {
	path := CopilotRootInstructionsPath(baseDir)
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	if strings.Contains(string(data), CopilotRootGeneratedMarker) {
		return os.Remove(path)
	}
	return nil
}

// -------------------------------------------------------------------
// Top-level convenience function
// -------------------------------------------------------------------

// CompileAgentsMD compiles AGENTS.md using the given config.
func CompileAgentsMD(baseDir string, cfg CompilationConfig) (*MergedResult, error) {
	compiler := New(baseDir)
	return compiler.Compile(cfg)
}
