// Package agentformatter provides CLAUDE.md and GEMINI.md formatters for APM compilation.
package agentformatter

import (
"path/filepath"
"strings"
)

// ClaudePlacement holds the result of CLAUDE.md placement analysis.
type ClaudePlacement struct {
ClaudePath          string
InstructionFiles    []string
AgentFiles          []string
Dependencies        []string
CoveragePatterns    []string
SourceAttribution   map[string]string
}

// ClaudeCompilationResult holds the result of CLAUDE.md compilation.
type ClaudeCompilationResult struct {
Success    bool
Placements []ClaudePlacement
ContentMap map[string]string // path -> content
Warnings   []string
Errors     []string
}

// GeminiPlacement holds the result of GEMINI.md placement analysis.
type GeminiPlacement struct {
GeminiPath       string
InstructionFiles []string
}

// GeminiCompilationResult holds the result of GEMINI.md compilation.
type GeminiCompilationResult struct {
Success    bool
Placements []GeminiPlacement
ContentMap map[string]string
Warnings   []string
Errors     []string
Stats      map[string]float64
}

// RenderGeminiStub generates the content for a GEMINI.md stub file.
func RenderGeminiStub(agentsPath string, version string) string {
rel := agentsPath
if rel == "" {
rel = "AGENTS.md"
}
var sb strings.Builder
sb.WriteString("<!-- Generated by APM CLI ")
sb.WriteString(version)
sb.WriteString(" -->\n")
sb.WriteString("<!-- Build ID: __BUILD_ID__ -->\n\n")
sb.WriteString("@")
sb.WriteString(filepath.ToSlash(rel))
sb.WriteString("\n")
return sb.String()
}

// RenderClaudeHeader returns the CLAUDE.md file header comment.
func RenderClaudeHeader() string {
return "<!-- Generated by APM CLI -->\n"
}

// SummarizeClaudeResult returns a human-readable summary of the compilation result.
func SummarizeClaudeResult(r *ClaudeCompilationResult) string {
if !r.Success {
return "[x] CLAUDE.md compilation failed: " + strings.Join(r.Errors, "; ")
}
return "[+] CLAUDE.md compiled successfully (" + itoa(len(r.Placements)) + " placement(s))"
}

func itoa(n int) string {
if n < 0 {
return "-" + itoa(-n)
}
if n < 10 {
return string(rune('0' + n))
}
return itoa(n/10) + string(rune('0'+n%10))
}
