package agentformatter_test

import (
	"strings"
	"testing"

	"github.com/githubnext/apm/internal/compilation/agentformatter"
)

func TestRenderGeminiStub(t *testing.T) {
	stub := agentformatter.RenderGeminiStub("AGENTS.md", "1.2.3")
	if !strings.Contains(stub, "<!-- Generated by APM CLI") {
		t.Error("stub should contain generated header")
	}
	if !strings.Contains(stub, "1.2.3") {
		t.Error("stub should contain version")
	}
	if !strings.Contains(stub, "@AGENTS.md") {
		t.Error("stub should contain @path reference")
	}
}

func TestRenderGeminiStubEmptyPath(t *testing.T) {
	stub := agentformatter.RenderGeminiStub("", "0.1.0")
	if !strings.Contains(stub, "@AGENTS.md") {
		t.Error("empty path should default to AGENTS.md")
	}
}

func TestRenderClaudeHeader(t *testing.T) {
	header := agentformatter.RenderClaudeHeader()
	if !strings.Contains(header, "Generated by APM CLI") {
		t.Error("claude header should contain 'Generated by APM CLI'")
	}
}

func TestSummarizeClaudeResultSuccess(t *testing.T) {
	r := &agentformatter.ClaudeCompilationResult{
		Success:    true,
		Placements: []agentformatter.ClaudePlacement{{}, {}},
	}
	summary := agentformatter.SummarizeClaudeResult(r)
	if !strings.Contains(summary, "[+]") {
		t.Error("success summary should contain [+]")
	}
	if !strings.Contains(summary, "2") {
		t.Error("success summary should mention placement count")
	}
}

func TestSummarizeClaudeResultFailure(t *testing.T) {
	r := &agentformatter.ClaudeCompilationResult{
		Success: false,
		Errors:  []string{"something went wrong"},
	}
	summary := agentformatter.SummarizeClaudeResult(r)
	if !strings.Contains(summary, "[x]") {
		t.Error("failure summary should contain [x]")
	}
	if !strings.Contains(summary, "something went wrong") {
		t.Error("failure summary should contain error message")
	}
}

func TestRenderGeminiStub_ContainsBuildID(t *testing.T) {
	stub := agentformatter.RenderGeminiStub("AGENTS.md", "1.0.0")
	if !strings.Contains(stub, "Build ID") {
		t.Error("stub should contain Build ID placeholder")
	}
}

func TestRenderGeminiStub_NonDefaultPath(t *testing.T) {
	stub := agentformatter.RenderGeminiStub("docs/AGENTS.md", "2.0.0")
	if !strings.Contains(stub, "docs/AGENTS.md") {
		t.Errorf("stub should contain path, got: %s", stub)
	}
}

func TestClaudePlacement_Fields(t *testing.T) {
	cp := agentformatter.ClaudePlacement{
		ClaudePath:       "CLAUDE.md",
		InstructionFiles: []string{"instructions.md"},
		AgentFiles:       []string{"agent.md"},
		Dependencies:     []string{"dep1"},
	}
	if cp.ClaudePath != "CLAUDE.md" {
		t.Errorf("ClaudePath = %q", cp.ClaudePath)
	}
	if len(cp.InstructionFiles) != 1 {
		t.Errorf("InstructionFiles len = %d", len(cp.InstructionFiles))
	}
}

func TestClaudeCompilationResult_ZeroValue(t *testing.T) {
	var r agentformatter.ClaudeCompilationResult
	if r.Success {
		t.Error("zero value Success should be false")
	}
	if len(r.Placements) != 0 {
		t.Error("zero value Placements should be empty")
	}
}

func TestGeminiCompilationResult_Fields(t *testing.T) {
	r := agentformatter.GeminiCompilationResult{
		Success:  true,
		Warnings: []string{"w1"},
		Stats:    map[string]float64{"coverage": 0.9},
	}
	if !r.Success {
		t.Error("expected Success true")
	}
	if r.Stats["coverage"] != 0.9 {
		t.Errorf("Stats coverage = %v", r.Stats["coverage"])
	}
}

func TestRenderClaudeHeader_NotEmpty(t *testing.T) {
	h := agentformatter.RenderClaudeHeader()
	if h == "" {
		t.Error("RenderClaudeHeader should not be empty")
	}
}

func TestSummarizeClaudeResult_MultipleErrors(t *testing.T) {
	r := &agentformatter.ClaudeCompilationResult{
		Success: false,
		Errors:  []string{"err1", "err2"},
	}
	summary := agentformatter.SummarizeClaudeResult(r)
	if !strings.Contains(summary, "err1") || !strings.Contains(summary, "err2") {
		t.Errorf("summary should contain all errors, got: %s", summary)
	}
}
