package agentformatter

import (
	"strings"
	"testing"
)

func TestRenderGeminiStub_EmptyPathFallback(t *testing.T) {
	s := RenderGeminiStub("", "1.0")
	if !strings.Contains(s, "@AGENTS.md") {
		t.Fatalf("expected @AGENTS.md, got %q", s)
	}
}

func TestRenderGeminiStub_CustomPath(t *testing.T) {
	s := RenderGeminiStub("docs/AGENTS.md", "2.0")
	if !strings.Contains(s, "@docs/AGENTS.md") {
		t.Fatalf("expected @docs/AGENTS.md, got %q", s)
	}
}

func TestRenderGeminiStub_VersionInOutput(t *testing.T) {
	s := RenderGeminiStub("", "3.5.1")
	if !strings.Contains(s, "3.5.1") {
		t.Fatalf("expected version 3.5.1 in output, got %q", s)
	}
}

func TestRenderGeminiStub_BuildIDComment(t *testing.T) {
	s := RenderGeminiStub("", "1.0")
	if !strings.Contains(s, "Build ID:") {
		t.Fatalf("expected 'Build ID:' in output, got %q", s)
	}
}

func TestRenderClaudeHeader_ExactValue(t *testing.T) {
	h := RenderClaudeHeader()
	if h != "<!-- Generated by APM CLI -->\n" {
		t.Fatalf("unexpected header: %q", h)
	}
}

func TestClaudePlacement_EmptySlicesNonNil(t *testing.T) {
	cp := ClaudePlacement{
		InstructionFiles: []string{},
		AgentFiles:       []string{},
		Dependencies:     []string{},
		CoveragePatterns: []string{},
	}
	if cp.InstructionFiles == nil {
		t.Fatal("InstructionFiles should not be nil")
	}
}

func TestClaudeCompilationResult_MultipleWarnings(t *testing.T) {
	r := &ClaudeCompilationResult{
		Success:  true,
		Warnings: []string{"w1", "w2", "w3"},
	}
	if len(r.Warnings) != 3 {
		t.Fatalf("expected 3 warnings, got %d", len(r.Warnings))
	}
}

func TestSummarizeClaudeResult_SinglePlacement(t *testing.T) {
	r := &ClaudeCompilationResult{
		Success:    true,
		Placements: []ClaudePlacement{{}},
	}
	s := SummarizeClaudeResult(r)
	if !strings.Contains(s, "1 placement") {
		t.Fatalf("expected '1 placement', got %q", s)
	}
}

func TestSummarizeClaudeResult_MultipleErrors2(t *testing.T) {
	r := &ClaudeCompilationResult{
		Success: false,
		Errors:  []string{"err1", "err2"},
	}
	s := SummarizeClaudeResult(r)
	if !strings.Contains(s, "err1") || !strings.Contains(s, "err2") {
		t.Fatalf("expected both errors in summary, got %q", s)
	}
}

func TestGeminiCompilationResult_StatsMap(t *testing.T) {
	r := GeminiCompilationResult{
		Stats: map[string]float64{"coverage": 0.95},
	}
	if r.Stats["coverage"] != 0.95 {
		t.Fatalf("expected 0.95, got %v", r.Stats["coverage"])
	}
}

func TestGeminiPlacement_InstructionFilesLen(t *testing.T) {
	gp := GeminiPlacement{
		GeminiPath:      "GEMINI.md",
		InstructionFiles: []string{"a.md", "b.md"},
	}
	if len(gp.InstructionFiles) != 2 {
		t.Fatalf("expected 2 instruction files, got %d", len(gp.InstructionFiles))
	}
}

func TestClaudeCompilationResult_ContentMap(t *testing.T) {
	r := ClaudeCompilationResult{
		Success:    true,
		ContentMap: map[string]string{"CLAUDE.md": "content"},
	}
	if r.ContentMap["CLAUDE.md"] != "content" {
		t.Fatalf("unexpected content map value")
	}
}
