package agentformatter_test

import (
	"strings"
	"testing"

	"github.com/githubnext/apm/internal/compilation/agentformatter"
)

func TestRenderGeminiStub(t *testing.T) {
	stub := agentformatter.RenderGeminiStub("AGENTS.md", "1.2.3")
	if !strings.Contains(stub, "<!-- Generated by APM CLI") {
		t.Error("stub should contain generated header")
	}
	if !strings.Contains(stub, "1.2.3") {
		t.Error("stub should contain version")
	}
	if !strings.Contains(stub, "@AGENTS.md") {
		t.Error("stub should contain @path reference")
	}
}

func TestRenderGeminiStubEmptyPath(t *testing.T) {
	stub := agentformatter.RenderGeminiStub("", "0.1.0")
	if !strings.Contains(stub, "@AGENTS.md") {
		t.Error("empty path should default to AGENTS.md")
	}
}

func TestRenderClaudeHeader(t *testing.T) {
	header := agentformatter.RenderClaudeHeader()
	if !strings.Contains(header, "Generated by APM CLI") {
		t.Error("claude header should contain 'Generated by APM CLI'")
	}
}

func TestSummarizeClaudeResultSuccess(t *testing.T) {
	r := &agentformatter.ClaudeCompilationResult{
		Success:    true,
		Placements: []agentformatter.ClaudePlacement{{}, {}},
	}
	summary := agentformatter.SummarizeClaudeResult(r)
	if !strings.Contains(summary, "[+]") {
		t.Error("success summary should contain [+]")
	}
	if !strings.Contains(summary, "2") {
		t.Error("success summary should mention placement count")
	}
}

func TestSummarizeClaudeResultFailure(t *testing.T) {
	r := &agentformatter.ClaudeCompilationResult{
		Success: false,
		Errors:  []string{"something went wrong"},
	}
	summary := agentformatter.SummarizeClaudeResult(r)
	if !strings.Contains(summary, "[x]") {
		t.Error("failure summary should contain [x]")
	}
	if !strings.Contains(summary, "something went wrong") {
		t.Error("failure summary should contain error message")
	}
}
